admin/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :settings
  resources :vehicles
  resources :drivers do
   collection do
      get     'approved'
      get     'declined'
   end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :static_pages do
    collection do
      get   'maps'
      get     'approved'
      get     'declined'
    end
  end

  namespace :api do
    #For Mobile
    namespace :v1 do
      resources :localities do
        collection do
        end
      end
      resources :trips do
        collection do
        end
      end
      resources :deals do
        collection do
        end
      end
      resources :master_settings do
        collection do
          get  'prices'
        end
      end
      resources :users do
        collection do
          post  'reset_password'
          post  'resent_verification'
        end
      end
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
      put 'users', to: 'users#update'
      patch 'users', to: 'users#update'
      put 'localities', to: 'localities#update'
      patch 'localities', to: 'localities#update'

    end
  end

  match '/customers',   to: 'users#index',   via: 'get'
  match '/customers/new',   to: 'users#new',   via: 'get'
  match '/customers/:id/edit',   to: 'users#edit',   via: 'get',   as: 'edit_customers'
  match '/customers/create',   to: 'users#create',   via: 'post'
  match '/customers/:id',   to: 'users#show',   via: 'get',   as: 'customer'
  match '/customers/:id',   to: 'users#update',   via: 'patch'
  match '/customers/:id',   to: 'users#update',   via: 'put'
  match '/customers/:id',   to: 'users#destroy',   via: 'delete'
  # match '/drivers',   to: 'users#drivers',   via: 'get'
  match '/dashboard',   to: 'static_pages#index',   via: 'get'
  match '/maps',   to: 'static_pages#maps',   via: 'get'

end

admin/app/models/booking.rb
class Booking < ApplicationRecord
end

admin/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:source, :destination, :distance, :price, :user_id, :source_name, :destination_name, :source_place_id, :destination_place_id)
    end
end

admin/app/helpers/bookings_helper.rb
module BookingsHelper
end

admin/app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :source_name %>
    <%= form.text_field :source_name %>
  </div>

  <div class="field">
    <%= form.label :destination_name %>
    <%= form.text_field :destination_name %>
  </div>

  <div class="field">
    <%= form.label :source_place_id %>
    <%= form.text_field :source_place_id %>
  </div>

  <div class="field">
    <%= form.label :destination_place_id %>
    <%= form.text_field :destination_place_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

admin/app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

admin/app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Destination</th>
      <th>Distance</th>
      <th>Price</th>
      <th>User</th>
      <th>Source name</th>
      <th>Destination name</th>
      <th>Source place</th>
      <th>Destination place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.source %></td>
        <td><%= booking.destination %></td>
        <td><%= booking.distance %></td>
        <td><%= booking.price %></td>
        <td><%= booking.user_id %></td>
        <td><%= booking.source_name %></td>
        <td><%= booking.destination_name %></td>
        <td><%= booking.source_place_id %></td>
        <td><%= booking.destination_place_id %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

admin/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

admin/app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @booking.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @booking.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @booking.distance %>
</p>

<p>
  <strong>Price:</strong>
  <%= @booking.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Source name:</strong>
  <%= @booking.source_name %>
</p>

<p>
  <strong>Destination name:</strong>
  <%= @booking.destination_name %>
</p>

<p>
  <strong>Source place:</strong>
  <%= @booking.source_place_id %>
</p>

<p>
  <strong>Destination place:</strong>
  <%= @booking.destination_place_id %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>