admin/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :settings
  resources :vehicles
  resources :drivers do
   collection do
      get     'approved'
      get     'declined'
   end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :static_pages do
    collection do
      get   'maps'
      get     'approved'
      get     'declined'
    end
  end

  namespace :api do
    #For Mobile
    namespace :v1 do
      resources :localities do
        collection do
        end
      end
      resources :trips do
        collection do
        end
      end
      resources :deals do
        collection do
        end
      end
      resources :master_settings do
        collection do
          get  'prices'
        end
      end
      resources :users do
        collection do
          post  'reset_password'
          post  'resent_verification'
        end
      end
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
      put 'users', to: 'users#update'
      patch 'users', to: 'users#update'
      put 'localities', to: 'localities#update'
      patch 'localities', to: 'localities#update'

    end
  end

  match '/customers',   to: 'users#index',   via: 'get'
  match '/customers/new',   to: 'users#new',   via: 'get'
  match '/customers/:id/edit',   to: 'users#edit',   via: 'get',   as: 'edit_customers'
  match '/customers/create',   to: 'users#create',   via: 'post'
  match '/customers/:id',   to: 'users#show',   via: 'get',   as: 'customer'
  match '/customers/:id',   to: 'users#update',   via: 'patch'
  match '/customers/:id',   to: 'users#update',   via: 'put'
  match '/customers/:id',   to: 'users#destroy',   via: 'delete'
  # match '/drivers',   to: 'users#drivers',   via: 'get'
  match '/dashboard',   to: 'static_pages#index',   via: 'get'
  match '/maps',   to: 'static_pages#maps',   via: 'get'

end

admin/app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

admin/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  def new
    @vehicle = Vehicle.new
  end

  def show
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to settings_path, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to settings_path, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to settings_path, notice: 'User was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:enable, :active, :icon, :map_icon, :name, :vehicle_type, :vehicle_id, :fee, :price)
  end
end

admin/app/views/vehicles/_form.html.erb
<!-- begin page-header -->
<%#= render 'layouts/static/header', header_title: params[:action] == 'new' ? 'Create New Users' : "Edit User - #{vehicle.first_name} #{vehicle.last_name}" %>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
    </div>
    <h4 class="panel-title lp-header">Settings</h4>
  </div>
  <div class="panel-body">
    <%= form_with(url: ((params[:action] == 'new' || params[:action] == 'create') ? "/vehicles/create" : "/vehicles/#{vehicle.id}"),model: vehicle, local: true, :html => {class: 'form-horizontal'}) do |form| %>
      <% if vehicle.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this client from being saved:</h2>
          <ul>
            <% vehicle.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group row m-b-15">
        <%= form.label :enable, 'Enable:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.check_box :enable, data: { render: 'switchery', theme: 'default', 'secondary-color': 'rgb(255, 91, 87)' }, checked: vehicle.enable %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :active, 'Active:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.check_box :active, data: { render: 'switchery', theme: 'default', 'secondary-color': 'rgb(255, 91, 87)' }, checked: vehicle.active %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :icon, 'Icon:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :icon, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :map_icon, 'Map Icon:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :map_icon, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :name, 'Name:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :vehicle_type, 'Type:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :vehicle_type, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :fee, 'Fee:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.number_field :fee, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :price, 'Per KM:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :price, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group row m-b-0">
        <label class="text-right col-md-2 col-sm-4 col-form-label">&nbsp;</label>
        <div class="col-md-9 col-sm-8">
          <%= form.submit 'Save', :class => 'btn btn-primary' %>
          &nbsp;&nbsp;<%= link_to 'Back', settings_path, :class => 'btn btn-default' %>
        </div>
      </div>
    <% end %>

  </div>
</div>
<!-- end panel -->

admin/app/views/vehicles/_table.html.erb
<table id="table_id" class="table table-bordered display">
  <thead>
  <tr>
    <th>Enabled</th>
    <th>Name</th>
    <th>Type</th>
    <th>Price</th>
    <th>First Fee</th>
    <th>Second Fee</th>
    <th>Third Fee</th>
    <th>Fourth Fee</th>
<!--    <th></th>-->
  </tr>
  </thead>
  <tbody>
    <% vehicles.each do |vehicle| %>
    <tr>
      <td><%= vehicle["enable"] ? "<i class='fas fa-check fa-2x text-success'></i>".html_safe : "<i class='fas fa-times fa-2x text-danger'></i>".html_safe %></td>
      <td><%= vehicle["name"] %></td>
      <td><%= vehicle["type"] %></td>
      <td><%= vehicle["price"] %></td>
      <td><%= vehicle["first_fee"] %></td>
      <td><%= vehicle["second_fee"] %></td>
      <td><%= vehicle["third_fee"] %></td>
      <td><%= vehicle["fourth_fee"] %></td>
<!--      <td>-->
<!--          <a class="btn btn-warning btn-xs" href="/vehicles/<%#= vehicle.id %>/edit"><i class="far fa-edit"></i></a>-->
<!--          <a data-confirm="Are you sure?" class="btn btn-danger btn-xs" rel="nofollow" data-method="delete" href="/vehicles/<%#= vehicle.id %>"><i class="fas fa-trash-alt"></i></a>-->
<!--      </td>-->

    </tr>
    <% end %>

  </tbody>
</table>
<%= link_to 'New Vehicle', new_vehicle_path, :class => 'btn btn-light' %>
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>

admin/app/views/vehicles/edit.html.erb
<%= render 'form', vehicle: @vehicle %>

admin/app/views/vehicles/new.html.erb
<%= render 'form', vehicle: @vehicle %>