admin/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :settings
  resources :vehicles
  resources :drivers do
   collection do
      get     'approved'
      get     'declined'
   end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :static_pages do
    collection do
      get   'maps'
      get     'approved'
      get     'declined'
    end
  end

  namespace :api do
    #For Mobile
    namespace :v1 do
      resources :localities do
        collection do
        end
      end
      resources :trips do
        collection do
        end
      end
      resources :deals do
        collection do
        end
      end
      resources :master_settings do
        collection do
          get  'prices'
        end
      end
      resources :users do
        collection do
          post  'reset_password'
          post  'resent_verification'
        end
      end
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
      put 'users', to: 'users#update'
      patch 'users', to: 'users#update'
      put 'localities', to: 'localities#update'
      patch 'localities', to: 'localities#update'

    end
  end

  match '/customers',   to: 'users#index',   via: 'get'
  match '/customers/new',   to: 'users#new',   via: 'get'
  match '/customers/:id/edit',   to: 'users#edit',   via: 'get',   as: 'edit_customers'
  match '/customers/create',   to: 'users#create',   via: 'post'
  match '/customers/:id',   to: 'users#show',   via: 'get',   as: 'customer'
  match '/customers/:id',   to: 'users#update',   via: 'patch'
  match '/customers/:id',   to: 'users#update',   via: 'put'
  match '/customers/:id',   to: 'users#destroy',   via: 'delete'
  # match '/drivers',   to: 'users#drivers',   via: 'get'
  match '/dashboard',   to: 'static_pages#index',   via: 'get'
  match '/maps',   to: 'static_pages#maps',   via: 'get'

end

admin/app/models/payment.rb
class Payment < ApplicationRecord
end

admin/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:holder_name, :card_number, :card_cvv, :card_expiry, :user_id)
    end
end

admin/app/helpers/payments_helper.rb
module PaymentsHelper
end

admin/app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :holder_name %>
    <%= form.text_field :holder_name %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_field :card_number %>
  </div>

  <div class="field">
    <%= form.label :card_cvv %>
    <%= form.text_field :card_cvv %>
  </div>

  <div class="field">
    <%= form.label :card_expiry %>
    <%= form.text_field :card_expiry %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

admin/app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

admin/app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Holder name</th>
      <th>Card number</th>
      <th>Card cvv</th>
      <th>Card expiry</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.holder_name %></td>
        <td><%= payment.card_number %></td>
        <td><%= payment.card_cvv %></td>
        <td><%= payment.card_expiry %></td>
        <td><%= payment.user_id %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

admin/app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

admin/app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Holder name:</strong>
  <%= @payment.holder_name %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @payment.card_number %>
</p>

<p>
  <strong>Card cvv:</strong>
  <%= @payment.card_cvv %>
</p>

<p>
  <strong>Card expiry:</strong>
  <%= @payment.card_expiry %>
</p>

<p>
  <strong>User:</strong>
  <%= @payment.user_id %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>