admin/config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :settings
  resources :vehicles
  resources :drivers do
   collection do
      get     'approved'
      get     'declined'
   end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :static_pages do
    collection do
      get   'maps'
      get     'approved'
      get     'declined'
    end
  end

  namespace :api do
    #For Mobile
    namespace :v1 do
      resources :localities do
        collection do
        end
      end
      resources :trips do
        collection do
        end
      end
      resources :deals do
        collection do
        end
      end
      resources :master_settings do
        collection do
          get  'prices'
        end
      end
      resources :users do
        collection do
          post  'reset_password'
          post  'resent_verification'
        end
      end
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
      put 'users', to: 'users#update'
      patch 'users', to: 'users#update'
      put 'localities', to: 'localities#update'
      patch 'localities', to: 'localities#update'

    end
  end

  match '/customers',   to: 'users#index',   via: 'get'
  match '/customers/new',   to: 'users#new',   via: 'get'
  match '/customers/:id/edit',   to: 'users#edit',   via: 'get',   as: 'edit_customers'
  match '/customers/create',   to: 'users#create',   via: 'post'
  match '/customers/:id',   to: 'users#show',   via: 'get',   as: 'customer'
  match '/customers/:id',   to: 'users#update',   via: 'patch'
  match '/customers/:id',   to: 'users#update',   via: 'put'
  match '/customers/:id',   to: 'users#destroy',   via: 'delete'
  # match '/drivers',   to: 'users#drivers',   via: 'get'
  match '/dashboard',   to: 'static_pages#index',   via: 'get'
  match '/maps',   to: 'static_pages#maps',   via: 'get'

end

admin/app/models/user.rb
class User < ApplicationRecord
  audited
  rolify
  has_one_attached :avatar
  extend Devise::Models
  attr_accessor :skip_password_validation
  before_save -> { skip_confirmation! }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  def full_name
    "#{self.first_name && self.first_name} #{self.last_name && self.last_name}"
  end

  def self.valid_login?(email, password)
    user = where(email: email).first
    if user && user.valid_password?(password)
      user.reset_authentication_token!
    end
    [user&.valid_password?(password), user]
  end

  def reset_authentication_token!
   update_column(:authentication_token, Devise.friendly_token)
  end

  def user_type
    if self.has_role? :driver
      "driver"
    else
      "user"
    end
  end


  protected
   def password_required?
     return false if skip_password_validation
     super
   end

end
``

admin/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_action :authenticate, only: [:update, :index]
  before_action :set_user, only: [:update]
  respond_to :json

  def reset_password
    @user = User.find_by_email(params[:email])
    if @user.present?
      @user.send_reset_password_instructions
      render :text => "updated"
    else
      render json: {"error":"Email doesn't exist."}, status: :unprocessable_entity
    end
  end

  def resent_verification
    @user = User.find_by_email(params[:email])
    if @user.present?
      @user.send_confirmation_instructions
      render json: {"success":"Account verification send to email."}, status: :ok
    else
      render json: {"error":"Email doesn't exist."}, status: :unprocessable_entity
    end
  end

  def index
    render json: current_user, methods: [:user_type], status: :ok
  end

  def update
    if !user_params.fetch(:password, '').empty?  # so it won't throw the ParameterMissing error
      if @user.update(user_params)
        render json: current_user, status: :ok
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    else
      if @user.update_without_password(user_params)
        render json: current_user, status: :ok
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    end
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :city, :phone_number, :email, :password, :password_confirmation)
  end
end

admin/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    if !user_signed_in?
      redirect_to(unauthenticated_root_path)
    else
      response = FirebaseApi.new.get("passengers")
      if response.success? && response.body
        @customers = response.body.values
      else
        @customers = []
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    response = FirebaseApi.new.get("passengers/#{params[:id]}")
    if response.success?
      @customer = response.body
    else
      @customer = {}
    end
  end

  # GET /drivers/new
  def new
  end

  # GET /drivers/1/edit
  def edit
    response = FirebaseApi.new.get("passengers/#{params[:id]}")
    if response.success?
      @customer = response.body
    else
      @customer = {}
    end
  end

  # POST /drivers
  # POST /drivers.json
  def create

    data = {
        first_name:  params[:first_name],
        middle_name:  params[:middle_name],
        last_name:  params[:last_name],
        present_address:  params[:address],
        gender:  params[:gender],
        birth_date:  params[:birth_date],
        email: params[:email],
        isPhoneVerified: false,
        name: params[:name],
        phoneNumber: params[:phone_number],
        uid: params[:uid],
        photoURL: "http://placehold.it/150x150"
    }
    FirebaseApi.new.update("passengers/#{params[:uid]}", data)
    redirect_to customers_path
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    response = FirebaseApi.new.get("passengers/#{params[:uid]}")
    if response.success?
      @customer = response.body
    else
      @customer = {}
    end
    data = {
        first_name:  params[:first_name],
        middle_name:  params[:middle_name],
        last_name:  params[:last_name],
        present_address:  params[:address],
        gender:  params[:gender],
        birth_date:  params[:birth_date],
        email: params[:email],
        isPhoneVerified: @customer['isPhoneVerified'],
        name: params[:name],
        password: @customer['password'],
        phoneNumber: params[:phone_number],
        uid: params[:uid],
        photoURL: @customer['photoURL']
    }
    FirebaseApi.new.set("passengers/#{params[:uid]}", data)
    redirect_to customers_path
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    FirebaseApi.new.delete("passengers/#{params[:id]}")
    redirect_to customers_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @customer = User.find(params[:id])
  end

  def set_roles
    if params[:is_user].present?
      @customer.add_role :user unless @customer.has_role? :user
    else
      @customer.remove_role :user if @customer.has_role? :user
    end

    if params[:is_driver].present?
      @customer.add_role :driver unless @customer.has_role? :driver
    else
      @customer.remove_role :driver if @customer.has_role? :driver
    end

    if params[:is_admin].present?
      @customer.add_role :admin unless @customer.has_role? :admin
    else
      @customer.remove_role :admin if @customer.has_role? :admin
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :city, :phone_number)
  end
end

admin/app/views/users/_fields.html.erb
<div class="form-group row m-b-15">
  <%= form.label :customer_type, 'customer Type:', class: 'text-right m-position-left col-md-2 col-sm-4 col-form-label' %>
  <div class="col-md-9 col-sm-8">
      <%= form.select :customer_type, options_for_select(['Driver'], (@carrier_contact.customer ? @carrier_contact.customer.customer_type : '')),{:include_blank => true}, class: 'form-control' %>
  </div>
</div>
<div class="form-group row m-b-15">
  <%= form.label :avatar, 'Avatar:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
  <div class="col-md-9 col-sm-8">
    <%= form.file_field :avatar %>
  </div>
</div>
<div class="form-group row m-b-15">
  <%= form.label :email, 'E-mail:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
  <div class="col-md-9 col-sm-8">
    <%= form.email_field :email, class: 'form-control' %>
  </div>
</div>
<div class="form-group row m-b-15">
  <%= form.label :password, 'Password:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
  <div class="col-md-9 col-sm-8">
    <%= form.password_field :password, class: 'form-control' %>
  </div>
</div>
<div class="form-group row m-b-15">
  <%= form.label :password_confirmation, 'Confirm Password:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
  <div class="col-md-9 col-sm-8">
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
</div>

admin/app/views/users/_form.html.erb
<!-- begin page-header -->
<%#= render 'layouts/static/header', header_title: params[:action] == 'new' ? 'Create New customers' : "Edit customer - #{customer.first_name} #{customer.last_name}" %>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
    </div>
    <h4 class="panel-title lp-header"><%= params[:action] == 'new' ? 'Create New customers' : "Edit customer - #{customer.first_name} #{customer.last_name}" %></h4>
  </div>
  <div class="panel-body">
    <%= form_with(url: ((params[:action] == 'new' || params[:action] == 'create') ? "/customers/create" : "/customers/#{customer.id}"),model: customer, local: true, :html => {class: 'form-horizontal', 'data-parsley-validate' => true}) do |form| %>
      <% if customer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(customer.errors.count, "error") %> prohibited this client from being saved:</h2>
          <ul>
            <% customer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group row m-b-15">
        <%= form.label :first_name, 'First Name:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :last_name, 'Last Name:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :avatar, 'Avatar:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.file_field :avatar %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :email, 'E-mail:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.email_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :password, 'Password:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.password_field :password, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :password_confirmation, 'Confirm Password:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <label class="text-right col-md-2 col-sm-4 col-form-label" >Admin</label>
        <div class="col-md-9 col-sm-8">
          <input type="checkbox" name="is_admin" data-render="switchery" data-theme="default" data-secondary-color="rgb(255, 91, 87)" <%= customer.has_role?(:admin) ? 'checked' : '' %>/>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <label class="text-right col-md-2 col-sm-4 col-form-label">Driver</label>
        <div class="col-md-9 col-sm-8">
          <input type="checkbox" name="is_driver" data-render="switchery" data-theme="default" data-secondary-color="rgb(255, 91, 87)" <%= (customer.has_role?(:driver) ||  params[:is_driver])? 'checked' : '' %>/>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <label class="text-right col-md-2 col-sm-4 col-form-label">customer</label>
        <div class="col-md-9 col-sm-8">
          <input type="checkbox" name="is_customer" data-render="switchery" data-theme="default" data-secondary-color="rgb(255, 91, 87)" <%= customer.has_role?(:customer) ? 'checked' : '' %>/>
        </div>
      </div>
      <div class="form-group row m-b-0">
        <label class="text-right col-md-2 col-sm-4 col-form-label">&nbsp;</label>
        <div class="col-md-9 col-sm-8">
          <%= form.submit 'Submit', :class => 'btn btn-primary' %>
          <% if params[:action] == 'edit' %>
            &nbsp;&nbsp;<a class="btn btn-info" href="/customers/<%= customer.id %>">Show</a>
          <% end %>
          <% if params[:action] == 'new' %>
            &nbsp;&nbsp;<%= link_to 'Back', customers_path, :class => 'btn btn-default' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- end panel -->

admin/app/views/users/_table.html.erb
<table id="table_id" class="table table-bordered display">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>City</th>
    <th>Phone</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% customers.each do |customer| %>
    <tr>
      <td><%= customer.full_name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.city %></td>
      <td><%= customer.phone_number %></td>
      <td>
          <a class="btn btn-warning btn-xs" href="/customers/<%= customer.id %>/edit"><i class="far fa-edit"></i></a>
          <a data-confirm="Are you sure?" class="btn btn-danger btn-xs" rel="nofollow" data-method="delete" href="/customers/<%= customer.id %>"><i class="fas fa-trash-alt"></i></a>
      </td>

    </tr>
    <% end %>

  </tbody>
</table>

<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>

admin/app/views/users/drivers.html.erb
<!-- begin page-header -->
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
      <%= link_to 'New Driver', customers_new_path(:is_driver => true), :class => 'btn btn-light btn-xs' %>
    </div>
    <h4 class="panel-title lp-header">Drivers</h4>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-bordered data-table-buttons display nowrap">
			<thead>
				<tr class="odd gradeX">
					<th>Name</th>
					<th>Email</th>
					<th>Phone #</th>
					<th>Ratings</th>
			    <th data-orderable="false">Actions</th>
				</tr>
			</thead>
			<tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer["name"] %></td>
						<td><%= customer["email"] %></td>
						<td><%= customer["phoneNumber"] %></td>
						<td>
							<div class="rating">
								<% @count = 1 %>
								<% while @count <= customer["rating"].to_i %>
									<span class="star active"></span>
									<% @count = @count + 1%>
								<% end %>
								<% @count = 1 %>
								<% @not_rated = 5 - customer["rating"].to_i %>
								<% while @count <= @not_rated %>
									<span class="star"></span>
									<% @count = @count + 1%>
								<% end %>
							</div>
						</td>
            <td>
              <a class="btn btn-warning btn-xs" href="/customers/<%= customer["uid"] %>/edit"><i class="far fa-edit"></i></a>
              <a data-confirm="Are you sure?" class="btn btn-danger btn-xs" rel="nofollow" data-method="delete" href="/customers/<%= customer["uid"] %>"><i class="fas fa-trash-alt"></i></a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<!-- end panel -->

admin/app/views/users/edit.html.erb
<!-- begin page-header -->
<%#= render 'layouts/static/header', header_title: params[:action] == 'new' ? 'Create New customers' : "Edit customer - #{customer.first_name} #{customer.last_name}" %>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
    </div>
    <h4 class="panel-title lp-header">Edit Customer</h4>
  </div>
  <div class="panel-body">
    <%= form_with(url: "/customers/#{@customer['uid']}", local: true, :method => :put, :html => {id: 'edit_customer', class: 'form-horizontal', 'data-parsley-validate' => true}) do |form| %>
      <%= form.hidden_field :uid, value: @customer['uid'] %>
      <div class="form-group row m-b-15">
        <%= form.label :first_name, 'First Name:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :first_name, class: 'form-control', value: @customer['first_name'], required: true %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :middle_name, 'Middle Name:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :middle_name, class: 'form-control', value: @customer['middle_name'] %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :last_name, 'Last Name:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :last_name, class: 'form-control', value: @customer['last_name'], required: true %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :phone_number, 'Phone Number:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :phone_number, class: 'form-control', value: @customer['phoneNumber'], required: true %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :address, 'Address:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.text_field :address, class: 'form-control', value: @customer['present_address'], required: true %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :gender, 'Gender:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.select :gender, options_for_select([['Female', 'female'], ['Male', 'male']], @customer['gender']), {:prompt => 'Select Gender'}, class: 'form-control', required: true %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :birth_date, 'Birth Date:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.date_field :birth_date, :class => 'form-control', value: @customer['birth_date'], placeholder: 'Birth Date', required: true %>
        </div>
      </div>
      <div class="form-group row m-b-15">
        <%= form.label :email, 'E-mail:', class: 'text-right col-md-2 col-sm-4 col-form-label' %>
        <div class="col-md-9 col-sm-8">
          <%= form.email_field :email, class: 'form-control', value: @customer['email'] %>
        </div>
      </div>
      <div class="form-group row m-b-0">
        <label class="text-right col-md-2 col-sm-4 col-form-label">&nbsp;</label>
        <div class="col-md-9 col-sm-8">
          <%= form.submit 'Submit', :class => 'btn btn-primary' %>
          &nbsp;&nbsp;<%= link_to 'Back', customers_path, :class => 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- end panel -->

admin/app/views/users/index.html.erb
<!-- begin page-header -->
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
      <%= link_to 'New Customers', customers_new_path, :class => 'btn btn-light btn-xs' %>
    </div>
    <h4 class="panel-title lp-header">customers</h4>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-bordered data-table-buttons display nowrap">
			<thead>
			<tr class="odd gradeX">
				<th>Name</th>
				<th>Gender</th>
				<th>Email</th>
				<th>Phone #</th>
				<th>Address</th>
				<th data-orderable="false">Actions</th>
			</tr>
			</thead>
			<tbody>
        <% @customers.each do |customer| %>
          <tr>
						<td><%= customer["first_name"] %> <%= customer["last_name"] %></td>
						<td><%= customer["gender"] %></td>
						<td><%= customer["email"] %></td>
						<td><%= customer["phoneNumber"] %></td>
						<td><%= customer["present_address"] %></td>
						<td>
							<a class="btn btn-warning btn-xs" href="/customers/<%= customer["uid"] %>/edit"><i class="far fa-edit"></i></a>
							<a data-confirm="Are you sure?" class="btn btn-danger btn-xs" rel="nofollow" data-method="delete" href="/customers/<%= customer["uid"] %>"><i class="fas fa-trash-alt"></i></a>
						</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<!-- end panel -->

admin/app/views/users/show.html.erb
<!-- begin page-header -->
<div class="header-violet">
  <h1 class="pull-left">
    <%= render 'layouts/static/header', header_title: generate_alphanumeric_id("#{@customer.first_name} #{@customer.last_name}", @customer.id), sub_header_title: "#{@customer.first_name} #{@customer.last_name}" %>
  </h1>
  <span class="pull-right">
    <%= link_to 'Edit', edit_customer_path(@customer), :class => 'btn btn-warning btn-xs' %>
    <%= link_to 'Back', customers_path, :class => 'btn btn-info btn-xs' %>
    <%= link_to 'Delete', @customer, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs'%>
  </span>
</div>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <!-- <div class="panel-heading">
    <div class="panel-heading-btn">

    </div>
  </div> -->
  <div class="panel-body">
    <h4 class="text-inverse">Details</h4>
    <div class="row">
      <label class="col-md-2 text-right m-position-left col-form-label">Administrator:</label>
      <div class="col-md-9 lbl-padding-t">
        <%= @customer.has_role?(:admin) ? "<i class='fas fa-check fa-2x text-success'></i>".html_safe : "<i class='fas fa-times fa-2x text-danger'></i>".html_safe %>
      </div>
    </div>
    <div class="row">
      <label class="col-md-2 text-right m-position-left col-form-label">Driver:</label>
      <div class="col-md-9 lbl-padding-t">
        <%= @customer.has_role?(:driver) ? "<i class='fas fa-check fa-2x text-success'></i>".html_safe : "<i class='fas fa-times fa-2x text-danger'></i>".html_safe %>
      </div>
    </div>
    <div class="row">
      <label class="col-md-2 text-right m-position-left col-form-label">customer:</label>
      <div class="col-md-9 lbl-padding-t">
        <%= @customer.has_role?(:customer) ? "<i class='fas fa-check fa-2x text-success'></i>".html_safe : "<i class='fas fa-times fa-2x text-danger'></i>".html_safe %>
      </div>
    </div>
    <div class="row">
      <label class="col-md-2 text-right m-position-left col-form-label">Name:</label>
      <div class="col-md-9 lbl-padding-t">
        <%= @customer.first_name.capitalize %>&nbsp;<%= @customer.last_name.capitalize %>
      </div>
    </div>

    <div class="row">
      <label class="col-md-2 text-right m-position-left col-form-label">E-mail:</label>
      <div class="col-md-9 lbl-padding-t">
        <%= @customer.email %>
      </div>
    </div>

  </div>
</div>
<!-- end panel -->